config/routes.rb
Oferts::Application.routes.draw do  
  namespace :ofert do
    get "all"=> "cupons#index", :as=> "all"
    get "/trabajos"=> "works#index", :as=> "trabajos"
    post "/trabajos"=> "works#index"
  end  
  root :to => 'home#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Oferts</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "popup.js" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "jquery.tools.min.js" %>
  <%= javascript_include_tag "analytics.js" %>
  <%= javascript_include_tag "jquery.hoverIntent.js" %>
  <%= javascript_include_tag "efect.js" %>  
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container_12">
  <div class="grid_12">
     <div class="grid_12">
      <br><br>
       <div class="grid_2">
         <%= image_tag 'rails.png' %>
       </div>     
       <div class="grid_2">
         <div class="grid_2">
           <%= link_to image_tag("welcome.gif", :size=> "150x150", :title=>"Bienvenida", :border=>0, :id=>'bienvenido'), root_path %>
         </div>       
         <div class="grid_2 flecha1 push_1" id="welcome_text_arrow" style="display:none;">
         <%= image_tag("arrow.gif", :border=>0 ) %>
        </div>
         <div class="grid_5 color1 norm2 chat" id="welcome_text" style="display:none;">
           <%= render 'home/welcome' %>
         </div> 
       </div>

       <div class="grid_2">
         <div class="grid_2">
           <%= link_to image_tag("buscador.gif", :size=> "150x150", :title=>"Buscador", :border=>0, :id=>'buscador'), ofert_trabajos_path %>
         </div>       
         <div class="grid_2 flecha1 push_1" id="busq_text_arrow" style="display:none;">
         <%= image_tag("arrow.gif", :border=>0 ) %>
        </div>
         <div class="grid_5 round color1 chat" id="buscador_text"  style="display:none;">
           <%= render 'home/buscador' %>
         </div>
       </div>

       <div class="grid_2">
         <div class="grid_2">
           <%= image_tag("curriculum.gif", :size=> "150x150", :title=>"curriculum", :border=>0, :id=>'curriculum' ) %>
         </div>       
         <div class="grid_2 flecha1 push_1" id="curri_text_arrow" style="display:none;">
         <%= image_tag("arrow.gif", :border=>0 ) %>
        </div>
         <div class="grid_5 round color1 chat" id="curriculum_text"  style="display:none">
          <%= render 'home/curriculum' %>
         </div>
       </div>    
     </div>
  </div>
  <div class="grid_12"><hr></div>  
  <%= yield %>
</div>
</body>
</html>